-- TC#2 ---
EXEC Create_Role ('THANH_TRA', null);
EXEC Create_Role ('BAC_SI', null);
EXEC Create_Role ('CoSo_YTe', null);
EXEC Create_Role ('NGHIEN_CUU', null);
EXEC Create_Role ('BENH_NHAN', null);

GRANT SELECT ON BENHNHAN TO THANH_TRA;
GRANT SELECT ON CSYT TO THANH_TRA;
GRANT SELECT ON HSBA TO THANH_TRA;
GRANT SELECT ON HSBA_DV TO THANH_TRA;
GRANT SELECT ON NHANVIEN TO THANH_TRA;

exec Grant_NewUser('Test02', 'Test02', N'Thanh Tra', 'CS6');

exec GRANT_ROLE_TO_USER ('THANH_TRA', 'Test02', null);

-- TC#3 --
---- TC#3
CREATE OR REPLACE VIEW NHANVIEN_CSYT_HSBA
AS 
(
  SELECT HS.*
  FROM HSBA HS
  WHERE HS.MACSYT = (SELECT NV.CSYT
                    FROM NHANVIEN NV
                    WHERE NV.MANV = 'USER')
);

CREATE OR REPLACE VIEW NHANVIEN_CSYT_HSBA_DV
AS 
(
  SELECT DV.*
  FROM NHANVIEN NV, CSYT CS, HSBA HS, HSBA_DV DV
  WHERE NV.CSYT = CS.MACSYT
  AND CS.MACSYT = HS.MACSYT
  AND HS.MAHSBA = DV.MAHSBA
  AND NV.MANV = 'USER'
);

SELECT * FROM NHANVIEN;
SELECT * FROM CSYT;
SELECT * FROM HSBA;
SELECT * FROM HSBA_DV;
SELECT * FROM BENHNHAN;

drop role CoSo_YTe;

CREATE ROLE CoSo_YTe;

GRANT CREATE SESSION TO CoSo_YTe;
GRANT INSERT, DELETE ON NHANVIEN_CSYT_HSBA TO CoSo_YTe;
GRANT INSERT, DELETE ON NHANVIEN_CSYT_HSBA_DV TO CoSo_YTe;

CREATE USER NV93 identified by NV93;

GRANT CREATE SESSION TO NV93;

GRANT CoSo_YTe TO NV93;