-- TC#2 ---
-- CHUA DUOC --
EXEC Create_Role ('BAC_SI','123');
EXEC Create_Role ('Y_TE','123');
EXEC Create_Role ('CoSo_YTe','123');
EXEC Create_Role ('NGHIEN_CUU','123');
EXEC Create_Role ('BENH_NHAN','123');

Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV69','Lom','Male',to_date('01-JAN-90','DD-MON-RR'),'ID010','Leon','722-6220','CS3','Thanh tra','');

Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV101','Ladw','Male',to_date('19-JAN-91','DD-MON-RR'),'ID011','Leo','700-6220','CS3', 'Cơ sở y tế','');

GRANT CREATE SESSION TO THANH_TRA;
GRANT SELECT ON BENHNHAN TO THANH_TRA;
GRANT SELECT ON CSYT TO THANH_TRA;
GRANT SELECT ON HSBA TO THANH_TRA;
GRANT SELECT ON HSBA_DV TO THANH_TRA;
GRANT SELECT ON NHANVIEN TO THANH_TRA;

EXEC Grant_NewUser('NV69','NV69');

exec GRANT_ROLE_TO_USER ('THANH_TRA', 'NV69', '');

-- CHAY DUOC --
CREATE ROLE THANH_TRA;

GRANT CREATE SESSION TO THANH_TRA;
GRANT SELECT ON BENHNHAN TO THANH_TRA;
GRANT SELECT ON CSYT TO THANH_TRA;
GRANT SELECT ON HSBA TO THANH_TRA;
GRANT SELECT ON HSBA_DV TO THANH_TRA;
GRANT SELECT ON NHANVIEN TO THANH_TRA;

CREATE USER NV69 identified by NV69;

GRANT CREATE SESSION TO THANH_TRA;

GRANT THANH_TRA TO NV69;

-- TC#3 --
---- TC#3
CREATE OR REPLACE VIEW NHANVIEN_CSYT_HSBA
AS 
(
  SELECT HS.*
  FROM HSBA HS
  WHERE HS.MACSYT = (SELECT NV.CSYT
                    FROM NHANVIEN NV
                    WHERE NV.MANV = 'USER')
);

CREATE OR REPLACE VIEW NHANVIEN_CSYT_HSBA_DV
AS 
(
  SELECT DV.*
  FROM NHANVIEN NV, CSYT CS, HSBA HS, HSBA_DV DV
  WHERE NV.CSYT = CS.MACSYT
  AND CS.MACSYT = HS.MACSYT
  AND HS.MAHSBA = DV.MAHSBA
  AND NV.MANV = 'USER'
);

SELECT * FROM NHANVIEN;
SELECT * FROM CSYT;
SELECT * FROM HSBA;
SELECT * FROM HSBA_DV;
SELECT * FROM BENHNHAN;

drop role CoSo_YTe;

CREATE ROLE CoSo_YTe;

GRANT CREATE SESSION TO CoSo_YTe;
GRANT INSERT, DELETE ON NHANVIEN_CSYT_HSBA TO CoSo_YTe;
GRANT INSERT, DELETE ON NHANVIEN_CSYT_HSBA_DV TO CoSo_YTe;

CREATE USER NV93 identified by NV93;

GRANT CREATE SESSION TO NV93;

GRANT CoSo_YTe TO NV93;