-- DBA
CREATE USER DBA_BV IDENTIFIED BY DBA_BV;
GRANT CREATE SESSION TO DBA_BV;
Grant DBA to DBA_BV;

-- Thanh Tra --
CREATE USER ThanhTra IDENTIFIED BY ThanhTra;
GRANT CREATE SESSION TO ThanhTra;

-- Cơ Sở Y Tế --
CREATE USER CS57 IDENTIFIED BY CS57;
GRANT CREATE SESSION TO CS57;

-- Nhân Viên --
CREATE USER NV5 IDENTIFIED BY NV5;
GRANT CREATE SESSION TO NV5;