-- DBA (Phân hệ 1 + 2)
CREATE USER DBA_BV IDENTIFIED BY DBA_BV;
GRANT CREATE SESSION TO DBA_BV;
Grant DBA to DBA_BV;

-- Thanh Tra --
exec Grant_NewUser('Test02', 'Test02', N'Thanh Tra', 'CS6');
exec GRANT_ROLE_TO_USER('Thanh_Tra', 'Test02', null);

-- Cơ Sở Y Tế --
CREATE USER CS57 IDENTIFIED BY CS57;
GRANT CREATE SESSION TO CS57;

-- Bác sĩ --
CREATE USER NV5 IDENTIFIED BY NV5;
GRANT CREATE SESSION TO NV5;

-- Bệnh Nhân --
CREATE USER BN0 IDENTIFIED BY BN0;
GRANT CREATE SESSION TO BN0;

-- Nghiên cứu --
CREATE USER NV96 IDENTIFIED BY NV96;
GRANT CREATE SESSION TO NV96;
