-- Delete item from recycle bin --
purge recyclebin;

-- Disable constraints --
begin
  for cur in 
    (select owner, constraint_name , table_name 
    from all_constraints
    where owner = 'DBA_BV')
    loop
     execute immediate 'ALTER TABLE '||cur.owner||'.'||cur.table_name||' MODIFY CONSTRAINT "'||cur.constraint_name||'" DISABLE ';
     --dbms_output.put_line('ALTER TABLE '||cur.owner||'.'||cur.table_name||' MODIFY CONSTRAINT "'||cur.constraint_name||'" DISABLE ');
  end loop;
end;
/

--------------------------------------------------------
--  File created - Friday-April-08-2022   
--------------------------------------------------------
-- INSERTING into BENHNHAN
SET DEFINE OFF;
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN95092889','CS79212387214637','Abraham Acevedo','11638',to_date('01-JAN-70','DD-MON-RR'),432,'7 Bridgeman Street','2','HA NOI','We must bear in mind that a closer study of the best practice patterns effectively changes the principles of the proper innovation of the strategic management.  ','That is to say a huge improvement of the strategic decision provides a deep insight into the conceptual design.  ','Bayfazon');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN9','CS09336147568','Retta Lord','86148',to_date('17-JUL-97','DD-MON-RR'),36,'9 Fortis Green Road','THU DUC','DA NANG','In respect that the grand strategy and growth opportunities of it are quite high.On the contrary, impact of the big impact may share attitudes on any predictable behavior.This may be done through the task analysis.','Speaking about comparison of the center of the comprehensive set of policy statements and primary element, components of the production cycle highlights the importance of an importance of the primary element.  ','Venlamalol');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN2038648','CS472365','Treena Lind','52432',to_date('04-JAN-13','DD-MON-RR'),96,'44B Acre Lane','7','HAI PHONG','In respect of a description of the matrix of available should keep its influence over the internal network.Therefore, the concept of the major outcomes can be treated as the only solution.','It is undeniable that the example of the consequential risks can hardly be compared with the general features and possibilities of the permanent growth.  ','Naposoprofen');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN1521','CS57','Hong Beaudoin','37879',to_date('23-MAY-05','DD-MON-RR'),272,'66 A-D Claylands Road','10','CAN THO','It is often said that final stages of the valuable information highlights the importance of the preliminary action plan.  ','For instance, a descriptive action of a number of the emergency planning the operating speed model the high performance of the entire picture.  ','Novotamsol');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN3248','CS0','Jason Blackmon','87267',to_date('15-SEP-99','DD-MON-RR'),551,'33-27 Philpot Street','BINH TAN','CAN THO','However, we can also agree that final stages of the basics of planning and scheduling definitely the entire picture the key principles and the questionable thesis.  ','Regardless of the fact that any further consideration the minor details of sources and influences of the competitive development and manufacturing the high performance of the efficient decision. The verification is quite a unconventional matter.  ','Lidohydrozon');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN67','CS79212387214637','Tiny Card','24206',to_date('10-MAY-01','DD-MON-RR'),2,'7 Cale Street','5','HA NOI','There is no doubt, that Kent Ã¡ is the firs person who formulated that the basic layout for in terms of the permanent growth minimizes influence of the irrelevance of limitation.  ','Which seems to confirm the idea that any further consideration commits resources to the first-class package. Thus a complete understanding is missing.  ','Irebutamde');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN50249752789','CS6','Carroll Binder','22554',to_date('03-JUN-83','DD-MON-RR'),355,'7 Upper Brook Street','8','HAI PHONG','To sort everything out, it is worth mentioning that details of the basic feature provides benefit from complete failure of the supposed theory.','There is no doubt, that Delbert BÃ¡ is the firs person who formulated that a huge improvement of the skills should set clear rules regarding what is conventionally known as subsequent actions.  ','Baytamdar');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN0','CS445','Maynard Brockman','93854',to_date('26-NOV-01','DD-MON-RR'),657,'41-46 Ada Street','3','DA NANG','What is more, the lack of knowledge of the growth of the market tendencies must be compatible with an initial attempt in development of the technical requirements.  ','One cannot deny that any further consideration the strategic management. The control is quite a crucial matter the flexible production planning and the minor details of final draft.  ','Laxospocose');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN927746','CS472365','Peggy Charlton','99298',to_date('01-JAN-70','DD-MON-RR'),63,'14 New Quebec Street','1','HA NOI','Perhaps we should also point out the fact that a closer study of the systolic approach should focus on the irrelevance of access.  ','It is stated that the evaluation of reliability activities for any of the key principles reliably the positive influence of any driving factor the hardware maintenance and the minor details of basic reason of the first-class package.  ','Acyclomuc');
Insert into BENHNHAN (MABN,MACSYT,TENBN,CMND,NGAYSINH,SONHA,"TENĐUONG",QUANHUYEN,TINHTP,TIENSUBENH,TIENSUBENHGD,DIUNGTHUOC) values ('BN83048','CS472365','Selene Cartwright','74883',to_date('23-APR-01','DD-MON-RR'),283,'4-9 Vale Lane','6','DA NANG','Which seems to confirm the idea that the results of the development process  impacts immensely on every vital decisions. In respect of the efficiency of the operational system presents a threat for the matrix of available.  ','It may reveal how the emergency planning successfully the major and minor objectives.Such tendency may immediately originate from the product functionality the vital decisions.This could easily be a result of a potential role models.','Baszodar');
-- INSERTING into CSYT
SET DEFINE OFF;
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS6','Australian High-Technologies Inc.','Tring','279-3549');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS57','International Telecom Group','Deal','721-5108');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS0','Western High-Technologies Co.','Blackpool','865-0016');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS09336147568','Australian Software Inc.','Nelson','454-9619');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS3','Home High-Technologies Corporation','Gloucester','115-6697');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS472365','Special High-Technologies Corp.','Abingdon','403-1635');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS4542637776','Creative Thermal Resources Group','Blackwood','693-4038');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS490','Australian Space Research Corp.','Longhope','410-3386');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS79212387214637','North Telemetrics Group','Ystrad Meurig','114-3354');
Insert into CSYT (MACSYT,TENCSYT,DCCSYT,SDTCSYT) values ('CS445','Creative V-Mobile Corp.','Rhayader','325-5419');
-- INSERTING into HSBA
SET DEFINE OFF;
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS98','BN2038648',to_date('10-SEP-14','DD-MON-RR'),'Even so, a number of brand new approaches has been tested during the the improvement of the well-known practice.In short, the explicit examination of prominent landmarks becomes a serious problem.','NV93','K8105QA62CA','CS490','It may reveal how the grand strategy habitually the general features and possibilities of the crucial development skills the questionable thesis.');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS84','BN0',to_date('16-MAR-02','DD-MON-RR'),'In any case, segments of the formal action cannot rely only on the ability bias.This seems to be a strongly obvious step towards the functional testing.','NV96','K91','CS57','To straighten it out, the example of the specific action result results in a complete compliance with the ultimate advantage of entire flexibility over alternate practices.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS278','BN83048',to_date('09-JAN-21','DD-MON-RR'),'Simplistically, the accurate predictions of the valuable information stimulates development of the more interactive services detection of the sources and influences of the participant evaluation sample.  ','NV93','KU4EU349M','CS4542637776','As a matter of fact the initial progress in the internal network the positive influence of any performance gaps the risks of an importance of the final draft.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS5337','BN3248',to_date('20-MAR-00','DD-MON-RR'),'In a loose sense any criterion boosts the growth of every contradiction between the production cycle and the specific decisions.  ','NV914','KHZ65P02','CS6','Moreover, the advantage of the formal action the potential role models.Thus a complete understanding is missing the high performance of the relational approach.This could seemingly be a result of a primary element.');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS2','BN0',to_date('02-MAR-84','DD-MON-RR'),'The real reason of the critical thinking differently this individual elements.Therefore, the concept of the application rules can be treated as the only solution.','NV727','K8U6X7X2839C','CS0','In a word, discussions of the treatment can hardly be compared with the market tendencies. The real reason of the optimization scenario presumably the irrelevance of investment the quality guidelines. Thus a complete understanding is missing.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS4489235','BN67',to_date('01-JAN-70','DD-MON-RR'),'However, we can also agree that the dominant cause of the skills has common features with the ultimate advantage of collective comprehension over alternate practices.  ','NV136292','KAKRMPHH','CS4542637776','Besides, the unification of the primary element has the potential to improve or transform the irrelevance of data.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS4','BN927746',to_date('07-MAY-04','DD-MON-RR'),'Nevertheless, one should accept that the negative impact of the competitive development and manufacturing has common features with an initial attempt in development of the first-class package.  ','NV93','K8T','CS0','The majority of examinations of the evident impacts show that the design patterns provides benefit from the first-class package. Thus a complete understanding is missing.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS13','BN50249752789',to_date('17-SEP-80','DD-MON-RR'),'One cannot deny that final stages of the individual elements should set clear rules regarding the quality guidelines.','NV32','KI','CS4542637776','Naturally, a closer study of the best practice patterns provides a glimpse at the irrelevance of factor.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS7168','BN927746',to_date('14-FEB-73','DD-MON-RR'),'To be more specific, concentration of a huge improvement of the predictable behavior the ultimate advantage of handy interference over alternate practices the sustainability of the project and any sweeping or enhanced approach.  ','NV5','K6EXSJ4','CS6','That is to say the conventional notion of a significant portion of the specific decisions gives us a clear notion of this major outcomes. This can eventually cause certain issues.  ');
Insert into HSBA (MAHSBA,MABN,NGAY,"CHANĐOAN",MABS,MAKHOA,MACSYT,KETLUAN) values ('HS344407','BN50249752789',to_date('04-JUL-21','DD-MON-RR'),'In respect that the independent knowledge and growth opportunities of it are quite high. From these facts, one may conclude that the point of the deep analysis provides a deep insight into the preliminary action plan.  ','NV32','K2S3M4K6OXA','CS57','Quite possibly, there is a direct relation between the fundamental problem and a description of the individual elements. However, some part of the product functionality represents basic principles of the conceptual design.  ');
-- INSERTING into HSBA_DV
SET DEFINE OFF;
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS344407','DV58',to_date('12-MAR-19','DD-MON-RR'),'NV5','In plain English, some of the strategic decision has become even more significant for the minor details of draft analysis and prior decisions and early design solutions.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS2','DV436',to_date('19-DEC-13','DD-MON-RR'),'NV93','In respect that any part of the structured technology analysis represents basic principles of the bilateral act.');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS98','DV4649810',to_date('13-SEP-94','DD-MON-RR'),'NV115081','To be honest, violations of the big impact becomes a serious problem. Therefore, the pursuance of functional testing poses problems and challenges for both the base configuration and the irrelevance of scale.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS4489235','DV5305544858717',to_date('13-MAY-72','DD-MON-RR'),'NV5','From these facts, one may conclude that components of the interpretation of the predictable behavior must be compatible with any productivity boost. This may be done through the driving factor.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS84','DV390108',to_date('05-DEC-99','DD-MON-RR'),'NV32','The most common argument against this is that within the framework of the the profit represents a bond between the structured technology analysis and the preliminary action plan.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS4','DV4829913790853078404',to_date('14-JUL-02','DD-MON-RR'),'NV4739063975','First and foremost, all approaches to the creation of the progress of the task analysis gives us a clear notion of the general features and possibilities of the first-class package.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS278','DV98276557035588',to_date('06-OCT-07','DD-MON-RR'),'NV96','The other side of the coin is, however, that the efficiency of the criterion provides a deep insight into the content testing method or the sources and influences of the source of permanent growth.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS13','DV334',to_date('04-AUG-77','DD-MON-RR'),'NV4739063975','It is stated that the raw draft of the flexible production planning should help in resolving present challenges.');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS5337','DV48',to_date('13-SEP-94','DD-MON-RR'),'NV914','Another way of looking at this problem is to admit that discussions of the basic feature should correlate with this predictable behavior. This can eventually cause certain issues.  ');
Insert into HSBA_DV (MAHSBA,MADV,NGAY,MAKTV,KETQUA) values ('HS7168','DV5607249227',to_date('05-DEC-99','DD-MON-RR'),'NV5','For instance, the optimization of the basic feature gives a complete experience of the more technical requirements of the final draft.');
-- INSERTING into NHANVIEN
SET DEFINE OFF;
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV84546617973','Christian Laporte','Male',to_date('01-JAN-70','DD-MON-RR'),'ID000','Ireland','309-5085','CS09336147568','Bác sĩ','Da liễu');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV5','Reynaldo Ackerman','Female',to_date('23-DEC-96','DD-MON-RR'),'ID001','Afghanistan','593-0812','CS0','Bác sĩ','Gây mê');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV727','Adalberto Aldrich','Male',to_date('15-OCT-18','DD-MON-RR'),'ID002','Philippines','452-5384','CS6','Bác sĩ','Da liễu');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV93','Temeka Higgs','Male',to_date('08-MAR-72','DD-MON-RR'),'ID003','Thailand','844-8614','CS4542637776','Nhân viên y tế','Da liễu');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV115081','Antonio Batson','Male',to_date('16-JUN-95','DD-MON-RR'),'ID004','Jordan','836-3030','CS0','Bác sĩ','Gây mê');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV32','Rick Speer','Female',to_date('08-NOV-02','DD-MON-RR'),'ID005','Ireland','895-1196','CS490','Nhân viên y tế','Gây mê');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV4739063975','Gary Penn','Male',to_date('05-NOV-07','DD-MON-RR'),'ID006','Nepal','447-4898','CS09336147568','Bác sĩ','Da liễu');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV914','Kent Crittenden','Female',to_date('01-JAN-70','DD-MON-RR'),'ID007','Suriname','522-1512','CS490','Bác sĩ','Gây mê');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV96','Larry Grissom','Male',to_date('01-JAN-70','DD-MON-RR'),'ID008','Lebanon','722-6550','CS3','Nhân viên y tế','Gây mê');
Insert into NHANVIEN (MANV,HOTEN,PHAI,NGAYSINH,CMND,QUEQUAN,SODT,CSYT,VAITRO,CHUYENKHOA) values ('NV136292','Abe Hatley','Male',to_date('22-FEB-05','DD-MON-RR'),'ID009','Albania','092-5487','CS57','Nhân viên y tế','Da liễu');

-- Enable constraints --
begin
  for cur in 
    (select owner, constraint_name , table_name 
    from all_constraints
    where owner = 'DBA_BV') 
    loop
     execute immediate 'ALTER TABLE '||cur.owner||'.'||cur.table_name||' MODIFY CONSTRAINT "'||cur.constraint_name||'" ENABLE ';
  end loop;
end;